### ISSUE TITLE
Improved repository description?

### ISSUE THREAD

**Issue by justinclift** [ossc-db/pg_hint_plan#178]
The existing description for this repository isn't great English:

```
Give PostgreSQL ability to manually force some decisions in execution plans. 
```

Is it ok to suggest improvements, maybe something like this?

```
Force PostgreSQL to execute query plans the way you want
```

... or maybe use "Tell PostgreSQL ..." there instead of "Force PostgreSQL ..."

What do you reckon? :smile:

**Comment by michaelpq** [comment]
I would suggest something even simpler, because we have a README that explains what this extension does:
```
Extension adding support for query hint plans in PostgreSQL.
```

@yamatattsu It happens that I don't have an access to that. Perhaps you could improve the description of this repository?

**Comment by justinclift** [comment]
> Extension adding support for query hint plans in PostgreSQL.

Yeah, that sounds good too. :smile:

**Comment by yamatattsu** [comment]
>
> <https://github.com/yamatattsu>
>
Hi Michael-san,

@yamatattsu <https://github.com/yamatattsu> It happens that I don't have an
> access to that. Perhaps you could improve the description of this
> repository?
>

Yeah, I can improve that probably.
So I'll fix that on this weekend.

**Comment by yamatattsu** [comment]
Hi Michael and Justin,

>Extension adding support for query hint plans in PostgreSQL

I realized "query hint plans" as Michael-san proposed seems like a
typo: s/query hint plans/query hint/ ?

Even if it was typo, the word "query hint" is not popular, so I'd like
to propose the following:

    Extension adding support for optimizer hints in PostgreSQL

It is good for the description because the word "optimizer hints" is
used on PostgreSQL wiki like this:

    https://wiki.postgresql.org/wiki/OptimizerHintsDiscussion

What do you guys think about that?

Regards,
Tatsuro Yamada

**Comment by justinclift** [comment]
> Extension adding support for optimizer hints in PostgreSQL

The phrase structure sounds good.  I'm unsure if "optimizer" is better than "query plan" hints though?  If "optimizer" is more accurate though, then this has my vote (for whatever that's worth). :wink:

**Comment by horiguti** [comment]
If the term 'optimizaer hints' is sufficiently widespread, I think it's appropriate to use it, considering that this tool doesn't always end up completely correcting plans.

**Comment by yamatattsu** [comment]
Hi Justin and Horiguti,

Thanks for the comments.
Since there is the PostgreSQL wiki page related to "optimizer hints" as I mentioned above, 
I believe it is a well-known term, so I'll use it in the description.

If it has a problem or something, let's consider a more suitable word and fix it again later.
   
Thanks,

**Comment by yamatattsu** [comment]
I'm going to close this issue because I fixed the description,

**Comment by justinclift** [comment]
Cool, seems good.  Thanks for getting it done. :smile:
