### ISSUE TITLE
pg_hint_plan build issue with PostgreSQL-10.8

### ISSUE THREAD

**Issue by semabtariq1** [ossc-db/pg_hint_plan#31]
I was trying to build pg_hint_plan with latest PostgreSQL-10.8 on centos-6 and 7 it fails. Please find the error detail below

```
core.c:1402:1: error: static declaration of 'is_dummy_rel' follows non-static declaration
 is_dummy_rel(RelOptInfo *rel)
 ^
In file included from pg_hint_plan.c:20:0:
PostgreSQL-inst-dir/10.8/include/server/nodes/relation.h:1195:13: note: previous declaration of 'is_dummy_rel' was here
 extern bool is_dummy_rel(RelOptInfo *rel);

```

**Comment by jk-shah** [comment]
It is broken for both 10.8 and 11.3 release with the fixes done I believe in this commit. 
https://github.com/postgres/postgres/commit/1d338584062b3e53b738f987ecb0d2b67745232a

pg_hint_plan for both 10 and 11 needs to be updated.

**Comment by yamatattsu** [comment]
Hi Jignesh,

It's been ages!
I'll ask Horiguchi-san who is maintaining this extension to fix the problem
when he comes back to Japan.
Because he joined PGConf at Ottawa, if my memory serves me correctly. :)

Thanks,
Tatsuro Yamada



2019年5月23日(木) 6:14 Jignesh Shah <notifications@github.com>:

**Comment by jk-shah** [comment]
Hi Tatsuro,

Any update?

Thanks.

**Comment by yamatattsu** [comment]
Hi Jignesh,

I tested your patch and it works fine but some regression test results were
changed between 10.8 and a previous version. Therefore, it takes a time to
release new version because we would be better to check the changes one by
one. I'll share the results on GitHub to lend Horiguchi-san's hand soon. :)

Thanks,
Tatsuro Yamada





2019年7月25日(木) 5:18 Jignesh Shah <notifications@github.com>:

**Comment by horiguti** [comment]
Sorry for the delay but it is alrady fixed.
