### ISSUE TITLE
Hint not working for Prepare Statement

### ISSUE THREAD

**Issue by ZaidGolwalaFAST** [ossc-db/pg_hint_plan#6]
I am trying to use pg_hint_plan to get hint for my dynamic queries prepared using Prepare statements , but hint does not work.

I have attached the test case for ECPG for which pg_hint_plan fails to provide hint.
From the log it seems the sequence in which it parses the query and execute the query gets jumbled up.

I have attached the log and Source code with my logging  for same , for debugging purpose I had added logging in functions "pg_hint_plan_post_parse_analyze" and "pg_hint_plan_planner".

It seems that while executing pg_hint_plan_planner the hint gets overwritten with next statement's hint string.

[test_douteki_01.pgc.txt](https://github.com/ossc-db/pg_hint_plan/files/1500564/test_douteki_01.pgc.txt)

[hint_plan.log](https://github.com/ossc-db/pg_hint_plan/files/1500562/hint_plan.log)

[pg_hint_plan.c.txt](https://github.com/ossc-db/pg_hint_plan/files/1500559/pg_hint_plan.c.txt)

**Comment by horiguti** [comment]
I think this is introduced at PG10 version and fixed by the commit https://github.com/ossc-db/pg_hint_plan/commit/0576a9485c3289d9a3bc49b63654cf8dcbe3fd04  @ master(PG12), https://github.com/ossc-db/pg_hint_plan/commit/4e3c9871ca22d4a5916c1d659787bca3cb09a184(PG11), https://github.com/ossc-db/pg_hint_plan/commit/eb2d8f38945415d347e580f8dedaa860ae5bd181(PG10).
