### ISSUE TITLE
why  any characters except alphabets, digits, spaces, underscores, commas and parentheses stops parsing immediately?

### ISSUE THREAD

**Issue by cstarc** [ossc-db/pg_hint_plan#77]
why  any characters except alphabets, digits, spaces, underscores, commas and parentheses stops parsing immediately? Why is it designed this way？ If there is no such restriction, will there be any problems?

**Comment by horiguti** [comment]
The reason is that we didn't want to truly parse the whole SQL query string.  Without that restriction, if some hint-like string accidentally occured in a text literal, pg_hint_plan would read it as hints.

pg_hint_plan 14 gets a new GUC parameter pg_hint_plan.hints_anywhere, whiich can allow read hints ignoring SQL syntax at all.
